// Generated by `dart run ffigen --config ffigen.sherpa_mnn.yaml`.
// Source: MNN d407447ed56c4121a11ccbd266dc184ca1ead0c2.
// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Narrow offline SenseVoice bindings generated from the pinned sherpa-mnn C API snapshot. Do not edit the generated Dart file by hand.
class SherpaMnnBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SherpaMnnBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SherpaMnnBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Accept input audio samples and compute the features.
  /// The user has to invoke SherpaMnnDecodeOfflineStream() to run the neural
  /// network and decoding.
  ///
  /// @param stream  A pointer returned by SherpaMnnCreateOfflineStream().
  /// @param sample_rate  Sample rate of the input samples. If it is different
  /// from config.feat_config.sample_rate, we will do
  /// resampling inside sherpa-mnn.
  /// @param samples A pointer to a 1-D array containing audio samples.
  /// The range of samples has to be normalized to [-1, 1].
  /// @param n  Number of elements in the samples array.
  ///
  /// @caution: For each offline stream, please invoke this function only once!
  void SherpaMnnAcceptWaveformOffline(
    ffi.Pointer<SherpaMnnOfflineStream> stream,
    int sample_rate,
    ffi.Pointer<ffi.Float> samples,
    int n,
  ) {
    return _SherpaMnnAcceptWaveformOffline(stream, sample_rate, samples, n);
  }

  late final _SherpaMnnAcceptWaveformOfflinePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SherpaMnnOfflineStream>,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('SherpaMnnAcceptWaveformOffline');
  late final _SherpaMnnAcceptWaveformOffline =
      _SherpaMnnAcceptWaveformOfflinePtr.asFunction<
        void Function(
          ffi.Pointer<SherpaMnnOfflineStream>,
          int,
          ffi.Pointer<ffi.Float>,
          int,
        )
      >();

  /// @param config  Config for the recognizer.
  /// @return Return a pointer to the recognizer. The user has to invoke
  /// SherpaMnnDestroyOfflineRecognizer() to free it to avoid memory
  /// leak.
  ffi.Pointer<SherpaMnnOfflineRecognizer> SherpaMnnCreateOfflineRecognizer(
    ffi.Pointer<SherpaMnnOfflineRecognizerConfig> config,
  ) {
    return _SherpaMnnCreateOfflineRecognizer(config);
  }

  late final _SherpaMnnCreateOfflineRecognizerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<SherpaMnnOfflineRecognizer> Function(
            ffi.Pointer<SherpaMnnOfflineRecognizerConfig>,
          )
        >
      >('SherpaMnnCreateOfflineRecognizer');
  late final _SherpaMnnCreateOfflineRecognizer =
      _SherpaMnnCreateOfflineRecognizerPtr.asFunction<
        ffi.Pointer<SherpaMnnOfflineRecognizer> Function(
          ffi.Pointer<SherpaMnnOfflineRecognizerConfig>,
        )
      >();

  /// Create an offline stream for accepting wave samples.
  ///
  /// @param recognizer  A pointer returned by SherpaMnnCreateOfflineRecognizer()
  /// @return Return a pointer to an OfflineStream. The user has to invoke
  /// SherpaMnnDestroyOfflineStream() to free it to avoid memory leak.
  ffi.Pointer<SherpaMnnOfflineStream> SherpaMnnCreateOfflineStream(
    ffi.Pointer<SherpaMnnOfflineRecognizer> recognizer,
  ) {
    return _SherpaMnnCreateOfflineStream(recognizer);
  }

  late final _SherpaMnnCreateOfflineStreamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<SherpaMnnOfflineStream> Function(
            ffi.Pointer<SherpaMnnOfflineRecognizer>,
          )
        >
      >('SherpaMnnCreateOfflineStream');
  late final _SherpaMnnCreateOfflineStream =
      _SherpaMnnCreateOfflineStreamPtr.asFunction<
        ffi.Pointer<SherpaMnnOfflineStream> Function(
          ffi.Pointer<SherpaMnnOfflineRecognizer>,
        )
      >();

  /// Decode an offline stream.
  ///
  /// We assume you have invoked SherpaMnnAcceptWaveformOffline() for the given
  /// stream before calling this function.
  ///
  /// @param recognizer A pointer returned by SherpaMnnCreateOfflineRecognizer().
  /// @param stream A pointer returned by SherpaMnnCreateOfflineStream()
  void SherpaMnnDecodeOfflineStream(
    ffi.Pointer<SherpaMnnOfflineRecognizer> recognizer,
    ffi.Pointer<SherpaMnnOfflineStream> stream,
  ) {
    return _SherpaMnnDecodeOfflineStream(recognizer, stream);
  }

  late final _SherpaMnnDecodeOfflineStreamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SherpaMnnOfflineRecognizer>,
            ffi.Pointer<SherpaMnnOfflineStream>,
          )
        >
      >('SherpaMnnDecodeOfflineStream');
  late final _SherpaMnnDecodeOfflineStream =
      _SherpaMnnDecodeOfflineStreamPtr.asFunction<
        void Function(
          ffi.Pointer<SherpaMnnOfflineRecognizer>,
          ffi.Pointer<SherpaMnnOfflineStream>,
        )
      >();

  /// Free a pointer returned by SherpaMnnCreateOfflineRecognizer()
  ///
  /// @param p A pointer returned by SherpaMnnCreateOfflineRecognizer()
  void SherpaMnnDestroyOfflineRecognizer(
    ffi.Pointer<SherpaMnnOfflineRecognizer> recognizer,
  ) {
    return _SherpaMnnDestroyOfflineRecognizer(recognizer);
  }

  late final _SherpaMnnDestroyOfflineRecognizerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SherpaMnnOfflineRecognizer>)
        >
      >('SherpaMnnDestroyOfflineRecognizer');
  late final _SherpaMnnDestroyOfflineRecognizer =
      _SherpaMnnDestroyOfflineRecognizerPtr.asFunction<
        void Function(ffi.Pointer<SherpaMnnOfflineRecognizer>)
      >();

  /// Destroy the pointer returned by SherpaMnnGetOfflineStreamResult().
  ///
  /// @param r A pointer returned by SherpaMnnGetOfflineStreamResult()
  void SherpaMnnDestroyOfflineRecognizerResult(
    ffi.Pointer<SherpaMnnOfflineRecognizerResult> r,
  ) {
    return _SherpaMnnDestroyOfflineRecognizerResult(r);
  }

  late final _SherpaMnnDestroyOfflineRecognizerResultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SherpaMnnOfflineRecognizerResult>)
        >
      >('SherpaMnnDestroyOfflineRecognizerResult');
  late final _SherpaMnnDestroyOfflineRecognizerResult =
      _SherpaMnnDestroyOfflineRecognizerResultPtr.asFunction<
        void Function(ffi.Pointer<SherpaMnnOfflineRecognizerResult>)
      >();

  /// Destroy an offline stream.
  ///
  /// @param stream A pointer returned by SherpaMnnCreateOfflineStream()
  void SherpaMnnDestroyOfflineStream(
    ffi.Pointer<SherpaMnnOfflineStream> stream,
  ) {
    return _SherpaMnnDestroyOfflineStream(stream);
  }

  late final _SherpaMnnDestroyOfflineStreamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SherpaMnnOfflineStream>)
        >
      >('SherpaMnnDestroyOfflineStream');
  late final _SherpaMnnDestroyOfflineStream =
      _SherpaMnnDestroyOfflineStreamPtr.asFunction<
        void Function(ffi.Pointer<SherpaMnnOfflineStream>)
      >();

  /// Get the result of the offline stream.
  ///
  /// We assume you have called SherpaMnnDecodeOfflineStream() or
  /// SherpaMnnDecodeMultipleOfflineStreams() with the given stream before
  /// calling this function.
  ///
  /// @param stream A pointer returned by SherpaMnnCreateOfflineStream().
  /// @return Return a pointer to the result. The user has to invoke
  /// SherpaMnnDestroyOnlineRecognizerResult() to free the returned
  /// pointer to avoid memory leak.
  ffi.Pointer<SherpaMnnOfflineRecognizerResult> SherpaMnnGetOfflineStreamResult(
    ffi.Pointer<SherpaMnnOfflineStream> stream,
  ) {
    return _SherpaMnnGetOfflineStreamResult(stream);
  }

  late final _SherpaMnnGetOfflineStreamResultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<SherpaMnnOfflineRecognizerResult> Function(
            ffi.Pointer<SherpaMnnOfflineStream>,
          )
        >
      >('SherpaMnnGetOfflineStreamResult');
  late final _SherpaMnnGetOfflineStreamResult =
      _SherpaMnnGetOfflineStreamResultPtr.asFunction<
        ffi.Pointer<SherpaMnnOfflineRecognizerResult> Function(
          ffi.Pointer<SherpaMnnOfflineStream>,
        )
      >();
}

/// It expects 16 kHz 16-bit single channel wave format.
final class SherpaMnnFeatureConfig extends ffi.Struct {
  /// Sample rate of the input data. MUST match the one expected
  /// by the model. For instance, it should be 16000 for models provided
  /// by us.
  @ffi.Int32()
  external int sample_rate;

  /// Feature dimension of the model.
  /// For instance, it should be 80 for models provided by us.
  @ffi.Int32()
  external int feature_dim;

  static ffi.Pointer<SherpaMnnFeatureConfig> $allocate(
    ffi.Allocator $allocator, {
    required int sample_rate,
    required int feature_dim,
  }) => $allocator<SherpaMnnFeatureConfig>()
    ..ref.sample_rate = sample_rate
    ..ref.feature_dim = feature_dim;
}

/// If the callback returns 0, then it stops generating
/// If the callback returns 1, then it keeps generating
typedef SherpaMnnGeneratedAudioCallback =
    ffi.Pointer<ffi.NativeFunction<SherpaMnnGeneratedAudioCallbackFunction>>;
typedef SherpaMnnGeneratedAudioCallbackFunction = ffi.Int32 Function(
  ffi.Pointer<ffi.Float> samples,
  ffi.Int32 n,
);
typedef DartSherpaMnnGeneratedAudioCallbackFunction = int Function(
  ffi.Pointer<ffi.Float> samples,
  int n,
);
typedef SherpaMnnGeneratedAudioCallbackWithArg =
    ffi.Pointer<
      ffi.NativeFunction<SherpaMnnGeneratedAudioCallbackWithArgFunction>
    >;
typedef SherpaMnnGeneratedAudioCallbackWithArgFunction = ffi.Int32 Function(
  ffi.Pointer<ffi.Float> samples,
  ffi.Int32 n,
  ffi.Pointer<ffi.Void> arg,
);
typedef DartSherpaMnnGeneratedAudioCallbackWithArgFunction = int Function(
  ffi.Pointer<ffi.Float> samples,
  int n,
  ffi.Pointer<ffi.Void> arg,
);
typedef SherpaMnnGeneratedAudioProgressCallback =
    ffi.Pointer<
      ffi.NativeFunction<SherpaMnnGeneratedAudioProgressCallbackFunction>
    >;
typedef SherpaMnnGeneratedAudioProgressCallbackFunction = ffi.Int32 Function(
  ffi.Pointer<ffi.Float> samples,
  ffi.Int32 n,
  ffi.Float p,
);
typedef DartSherpaMnnGeneratedAudioProgressCallbackFunction = int Function(
  ffi.Pointer<ffi.Float> samples,
  int n,
  double p,
);
typedef SherpaMnnGeneratedAudioProgressCallbackWithArg =
    ffi.Pointer<
      ffi.NativeFunction<SherpaMnnGeneratedAudioProgressCallbackWithArgFunction>
    >;
typedef SherpaMnnGeneratedAudioProgressCallbackWithArgFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Float> samples,
      ffi.Int32 n,
      ffi.Float p,
      ffi.Pointer<ffi.Void> arg,
    );
typedef DartSherpaMnnGeneratedAudioProgressCallbackWithArgFunction =
    int Function(
      ffi.Pointer<ffi.Float> samples,
      int n,
      double p,
      ffi.Pointer<ffi.Void> arg,
    );

final class SherpaMnnOfflineFireRedAsrModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> encoder;

  external ffi.Pointer<ffi.Char> decoder;

  static ffi.Pointer<SherpaMnnOfflineFireRedAsrModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
  }) => $allocator<SherpaMnnOfflineFireRedAsrModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder;
}

final class SherpaMnnOfflineLMConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> model;

  @ffi.Float()
  external double scale;

  static ffi.Pointer<SherpaMnnOfflineLMConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required double scale,
  }) => $allocator<SherpaMnnOfflineLMConfig>()
    ..ref.model = model
    ..ref.scale = scale;
}

final class SherpaMnnOfflineModelConfig extends ffi.Struct {
  external SherpaMnnOfflineTransducerModelConfig transducer;

  external SherpaMnnOfflineParaformerModelConfig paraformer;

  external SherpaMnnOfflineNemoEncDecCtcModelConfig nemo_ctc;

  external SherpaMnnOfflineWhisperModelConfig whisper;

  external SherpaMnnOfflineTdnnModelConfig tdnn;

  external ffi.Pointer<ffi.Char> tokens;

  @ffi.Int32()
  external int num_threads;

  @ffi.Int32()
  external int debug;

  external ffi.Pointer<ffi.Char> provider;

  external ffi.Pointer<ffi.Char> model_type;

  /// Valid values:
  /// - cjkchar
  /// - bpe
  /// - cjkchar+bpe
  external ffi.Pointer<ffi.Char> modeling_unit;

  external ffi.Pointer<ffi.Char> bpe_vocab;

  external ffi.Pointer<ffi.Char> telespeech_ctc;

  external SherpaMnnOfflineSenseVoiceModelConfig sense_voice;

  external SherpaMnnOfflineMoonshineModelConfig moonshine;

  external SherpaMnnOfflineFireRedAsrModelConfig fire_red_asr;
}

final class SherpaMnnOfflineMoonshineModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> preprocessor;

  external ffi.Pointer<ffi.Char> encoder;

  external ffi.Pointer<ffi.Char> uncached_decoder;

  external ffi.Pointer<ffi.Char> cached_decoder;

  static ffi.Pointer<SherpaMnnOfflineMoonshineModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> preprocessor,
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> uncached_decoder,
    required ffi.Pointer<ffi.Char> cached_decoder,
  }) => $allocator<SherpaMnnOfflineMoonshineModelConfig>()
    ..ref.preprocessor = preprocessor
    ..ref.encoder = encoder
    ..ref.uncached_decoder = uncached_decoder
    ..ref.cached_decoder = cached_decoder;
}

final class SherpaMnnOfflineNemoEncDecCtcModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaMnnOfflineNemoEncDecCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaMnnOfflineNemoEncDecCtcModelConfig>()..ref.model = model;
}

final class SherpaMnnOfflineParaformerModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaMnnOfflineParaformerModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaMnnOfflineParaformerModelConfig>()..ref.model = model;
}

final class SherpaMnnOfflineRecognizer extends ffi.Opaque {}

final class SherpaMnnOfflineRecognizerConfig extends ffi.Struct {
  external SherpaMnnFeatureConfig feat_config;

  external SherpaMnnOfflineModelConfig model_config;

  external SherpaMnnOfflineLMConfig lm_config;

  external ffi.Pointer<ffi.Char> decoding_method;

  @ffi.Int32()
  external int max_active_paths;

  /// Path to the hotwords.
  external ffi.Pointer<ffi.Char> hotwords_file;

  /// Bonus score for each token in hotwords.
  @ffi.Float()
  external double hotwords_score;

  external ffi.Pointer<ffi.Char> rule_fsts;

  external ffi.Pointer<ffi.Char> rule_fars;

  @ffi.Float()
  external double blank_penalty;
}

final class SherpaMnnOfflineRecognizerResult extends ffi.Struct {
  external ffi.Pointer<ffi.Char> text;

  /// Pointer to continuous memory which holds timestamps
  ///
  /// It is NULL if the model does not support timestamps
  external ffi.Pointer<ffi.Float> timestamps;

  /// number of entries in timestamps
  @ffi.Int32()
  external int count;

  /// Pointer to continuous memory which holds string based tokens
  /// which are separated by \0
  external ffi.Pointer<ffi.Char> tokens;

  /// a pointer array containing the address of the first item in tokens
  external ffi.Pointer<ffi.Pointer<ffi.Char>> tokens_arr;

  /// Return a json string.
  ///
  /// The returned string contains:
  /// {
  /// "text": "The recognition result",
  /// "tokens": [x, x, x],
  /// "timestamps": [x, x, x],
  /// "segment": x,
  /// "start_time": x,
  /// "is_final": true|false
  /// }
  external ffi.Pointer<ffi.Char> json;

  /// return recognized language
  external ffi.Pointer<ffi.Char> lang;

  /// return emotion.
  external ffi.Pointer<ffi.Char> emotion;

  /// return event.
  external ffi.Pointer<ffi.Char> event;

  static ffi.Pointer<SherpaMnnOfflineRecognizerResult> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> text,
    required ffi.Pointer<ffi.Float> timestamps,
    required int count,
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> tokens_arr,
    required ffi.Pointer<ffi.Char> json,
    required ffi.Pointer<ffi.Char> lang,
    required ffi.Pointer<ffi.Char> emotion,
    required ffi.Pointer<ffi.Char> event,
  }) => $allocator<SherpaMnnOfflineRecognizerResult>()
    ..ref.text = text
    ..ref.timestamps = timestamps
    ..ref.count = count
    ..ref.tokens = tokens
    ..ref.tokens_arr = tokens_arr
    ..ref.json = json
    ..ref.lang = lang
    ..ref.emotion = emotion
    ..ref.event = event;
}

final class SherpaMnnOfflineSenseVoiceModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> model;

  external ffi.Pointer<ffi.Char> language;

  @ffi.Int32()
  external int use_itn;

  static ffi.Pointer<SherpaMnnOfflineSenseVoiceModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required ffi.Pointer<ffi.Char> language,
    required int use_itn,
  }) => $allocator<SherpaMnnOfflineSenseVoiceModelConfig>()
    ..ref.model = model
    ..ref.language = language
    ..ref.use_itn = use_itn;
}

typedef SherpaMnnOfflineSpeakerDiarizationProgressCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        SherpaMnnOfflineSpeakerDiarizationProgressCallbackFunction
      >
    >;
typedef SherpaMnnOfflineSpeakerDiarizationProgressCallbackFunction =
    ffi.Int32 Function(
      ffi.Int32 num_processed_chunks,
      ffi.Int32 num_total_chunks,
      ffi.Pointer<ffi.Void> arg,
    );
typedef DartSherpaMnnOfflineSpeakerDiarizationProgressCallbackFunction =
    int Function(
      int num_processed_chunks,
      int num_total_chunks,
      ffi.Pointer<ffi.Void> arg,
    );
typedef SherpaMnnOfflineSpeakerDiarizationProgressCallbackNoArg =
    ffi.Pointer<
      ffi.NativeFunction<
        SherpaMnnOfflineSpeakerDiarizationProgressCallbackNoArgFunction
      >
    >;
typedef SherpaMnnOfflineSpeakerDiarizationProgressCallbackNoArgFunction =
    ffi.Int32 Function(
      ffi.Int32 num_processed_chunks,
      ffi.Int32 num_total_chunks,
    );
typedef DartSherpaMnnOfflineSpeakerDiarizationProgressCallbackNoArgFunction =
    int Function(int num_processed_chunks, int num_total_chunks);

final class SherpaMnnOfflineStream extends ffi.Opaque {}

final class SherpaMnnOfflineTdnnModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaMnnOfflineTdnnModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaMnnOfflineTdnnModelConfig>()..ref.model = model;
}

/// Please refer to
/// https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html
/// to download pre-trained models. That is, you can find encoder-xxx.onnx
/// decoder-xxx.onnx, and joiner-xxx.onnx for this struct
/// from there.
final class SherpaMnnOfflineTransducerModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> encoder;

  external ffi.Pointer<ffi.Char> decoder;

  external ffi.Pointer<ffi.Char> joiner;

  static ffi.Pointer<SherpaMnnOfflineTransducerModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> joiner,
  }) => $allocator<SherpaMnnOfflineTransducerModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.joiner = joiner;
}

final class SherpaMnnOfflineWhisperModelConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> encoder;

  external ffi.Pointer<ffi.Char> decoder;

  external ffi.Pointer<ffi.Char> language;

  external ffi.Pointer<ffi.Char> task;

  @ffi.Int32()
  external int tail_paddings;

  static ffi.Pointer<SherpaMnnOfflineWhisperModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> language,
    required ffi.Pointer<ffi.Char> task,
    required int tail_paddings,
  }) => $allocator<SherpaMnnOfflineWhisperModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.language = language
    ..ref.task = task
    ..ref.tail_paddings = tail_paddings;
}
